"""Constants for SportSync integration."""
from __future__ import annotations

from typing import Final

DOMAIN: Final = "sportsync"

# Config keys
CONF_FAVORITE_SPORTS: Final = "favorite_sports"
CONF_FAVORITE_TEAMS: Final = "favorite_teams"
CONF_FAVORITE_LEAGUES: Final = "favorite_leagues"
CONF_FAVORITE_TITLES: Final = "favorite_titles"
CONF_FAVORITE_CHANNELS: Final = "favorite_channels"
CONF_SCAN_INTERVAL: Final = "scan_interval"

# Defaults
DEFAULT_SCAN_INTERVAL: Final = 1800  # 30 minutes

# Sport types with metadata
SPORT_TYPES: Final[dict[str, dict[str, str]]] = {
    "football": {"name": "Football", "icon": "mdi:soccer", "emoji": "⚽"},
    "hockey": {"name": "Ice Hockey", "icon": "mdi:hockey-puck", "emoji": "🏒"},
    "basketball": {"name": "Basketball", "icon": "mdi:basketball", "emoji": "🏀"},
    "tennis": {"name": "Tennis", "icon": "mdi:tennis", "emoji": "🎾"},
    "golf": {"name": "Golf", "icon": "mdi:golf", "emoji": "⛳"},
    "handball": {"name": "Handball", "icon": "mdi:handball", "emoji": "🤾"},
    "motorsport": {"name": "Motorsport", "icon": "mdi:racing-helmet", "emoji": "🏎️"},
    "cycling": {"name": "Cycling", "icon": "mdi:bike", "emoji": "🚴"},
    "skiing": {"name": "Cross-country Skiing", "icon": "mdi:ski", "emoji": "⛷️"},
    "biathlon": {"name": "Biathlon", "icon": "mdi:target", "emoji": "🎯"},
    "alpine": {"name": "Alpine Skiing", "icon": "mdi:ski", "emoji": "⛷️"},
    "athletics": {"name": "Athletics", "icon": "mdi:run", "emoji": "🏃"},
    "swimming": {"name": "Swimming", "icon": "mdi:swim", "emoji": "🏊"},
    "boxing": {"name": "Boxing", "icon": "mdi:boxing-glove", "emoji": "🥊"},
    "mma": {"name": "MMA", "icon": "mdi:karate", "emoji": "🥋"},
    "american_football": {"name": "American Football", "icon": "mdi:football", "emoji": "🏈"},
    "baseball": {"name": "Baseball", "icon": "mdi:baseball", "emoji": "⚾"},
    "volleyball": {"name": "Volleyball", "icon": "mdi:volleyball", "emoji": "🏐"},
    "table_tennis": {"name": "Table Tennis", "icon": "mdi:table-tennis", "emoji": "🏓"},
    "badminton": {"name": "Badminton", "icon": "mdi:badminton", "emoji": "🏸"},
    "rugby": {"name": "Rugby", "icon": "mdi:rugby", "emoji": "🏉"},
    "horse_racing": {"name": "Horse Racing", "icon": "mdi:horse", "emoji": "🏇"},
    "snooker": {"name": "Snooker/Billiards", "icon": "mdi:billiards", "emoji": "🎱"},
    "darts": {"name": "Darts", "icon": "mdi:bullseye-arrow", "emoji": "🎯"},
    "padel": {"name": "Padel", "icon": "mdi:tennis", "emoji": "🎾"},
    "floorball": {"name": "Floorball", "icon": "mdi:hockey-sticks", "emoji": "🏑"},
    "bandy": {"name": "Bandy", "icon": "mdi:hockey-sticks", "emoji": "🏑"},
    "curling": {"name": "Curling", "icon": "mdi:curling", "emoji": "🥌"},
    "esports": {"name": "Esports", "icon": "mdi:controller", "emoji": "🎮"},
    "sailing": {"name": "Sailing", "icon": "mdi:sail-boat", "emoji": "⛵"},
    "winter_sports": {"name": "Winter Sports", "icon": "mdi:snowflake", "emoji": "❄️"},
    "freestyle_skiing": {"name": "Freestyle Skiing", "icon": "mdi:ski", "emoji": "⛷️"},
    "ski_jumping": {"name": "Ski Jumping", "icon": "mdi:ski", "emoji": "⛷️"},
    "nordic_combined": {"name": "Nordic Combined", "icon": "mdi:ski", "emoji": "⛷️"},
    "snowboard": {"name": "Snowboard", "icon": "mdi:snowboard", "emoji": "🏂"},
    "speed_skating": {"name": "Speed Skating", "icon": "mdi:skate", "emoji": "⛸️"},
    "other": {"name": "Other", "icon": "mdi:trophy", "emoji": "🏆"},
}

# Sport keyword mappings for auto-detection
SPORT_KEYWORDS: Final[dict[str, str]] = {
    # Football - Leagues and competitions
    "fotboll": "football",
    "soccer": "football",
    "premier league": "football",
    "la liga": "football",
    "serie a": "football",
    "bundesliga": "football",
    "allsvenskan": "football",
    "superettan": "football",
    "champions league": "football",
    "europa league": "football",
    "conference league": "football",
    "fotbolls-vm": "football",
    "fotbolls-em": "football",
    "vm-kval fotboll": "football",
    "em-kval fotboll": "football",
    "nations league": "football",
    "vm i fotboll": "football",
    "em i fotboll": "football",
    "eredivisie": "football",
    "ligue 1": "football",
    "primeira liga": "football",
    "scottish premiership": "football",
    "ekstraklasa": "football",
    "süper lig": "football",
    "super lig": "football",
    # Football - Major European clubs (for detection when only club names appear)
    "real madrid": "football",
    "barcelona": "football",
    "atletico madrid": "football",
    "real betis": "football",
    "sevilla fc": "football",
    "valencia cf": "football",
    "villarreal": "football",
    "real sociedad": "football",
    "celta de vigo": "football",
    "rayo vallecano": "football",
    "manchester united": "football",
    "manchester city": "football",
    "liverpool": "football",
    "chelsea": "football",
    "arsenal": "football",
    "tottenham": "football",
    "aston villa": "football",
    "nottingham forest": "football",
    "crystal palace": "football",
    "newcastle": "football",
    "bayern": "football",
    "dortmund": "football",
    "leipzig": "football",
    "leverkusen": "football",
    "vfb stuttgart": "football",
    "fsv mainz": "football",
    "freiburg": "football",
    "fc salzburg": "football",
    "red bull salzburg": "football",
    "juventus": "football",
    "inter milan": "football",
    "ac milan": "football",
    "napoli": "football",
    "roma": "football",
    "fiorentina": "football",
    "bologna": "football",
    "lazio": "football",
    "psg": "football",
    "paris saint": "football",
    "marseille": "football",
    "lyon": "football",
    "monaco": "football",
    "lille": "football",
    "nice": "football",
    "strasbourg": "football",
    "ajax": "football",
    "psv": "football",
    "feyenoord": "football",
    "az alkmaar": "football",
    "fc utrecht": "football",
    "go ahead eagles": "football",
    "porto": "football",
    "benfica": "football",
    "sporting": "football",
    "braga": "football",
    "celtic": "football",
    "rangers": "football",
    "aberdeen": "football",
    "galatasaray": "football",
    "fenerbahçe": "football",
    "fenerbahce": "football",
    "besiktas": "football",
    "dinamo zagreb": "football",
    "ferencvaros": "football",
    "ferencváros": "football",
    "legia warszawa": "football",
    "lech poznań": "football",
    "lech poznan": "football",
    "raków częstochowa": "football",
    "rakow czestochowa": "football",
    "slavia prag": "football",
    "sparta prag": "football",
    "viktoria plzeň": "football",
    "viktoria plzen": "football",
    "sigma olomouc": "football",
    "slovan bratislava": "football",
    "shakhtar donetsk": "football",
    "dynamo kyiv": "football",
    "red star belgrade": "football",
    "röda stjärnan": "football",
    "panathinaikos": "football",
    "paok": "football",
    "aek athens": "football",
    "olympiakos": "football",
    "omonia nicosia": "football",
    "aek larnaca": "football",
    "maccabi tel aviv": "football",
    "rapid wien": "football",
    "sturm graz": "football",
    "basel": "football",
    "young boys": "football",
    "lausanne sport": "football",
    "genk": "football",
    "club brugge": "football",
    "anderlecht": "football",
    "fcsb": "football",
    "universitatea craiova": "football",
    "ludogorets": "football",
    "brann": "football",
    # Swedish football
    "malmö ff": "football",
    "malmo ff": "football",
    "bk häcken": "football",
    "bk hacken": "football",
    "djurgården": "football",
    "djurgarden": "football",
    "hammarby": "football",
    "aik": "football",
    "ifk göteborg": "football",
    "ifk goteborg": "football",
    "elfsborg": "football",
    # Finnish football
    "kuopion palloseura": "football",
    "kups": "football",
    # Other European clubs
    "jagiellonia": "football",
    "shamrock rovers": "football",
    "shelbourne": "football",
    "lincoln red imps": "football",
    "celje": "football",
    "rijeka": "football",
    "zrinjski": "football",
    "drita": "football",
    "shkendija": "football",
    "breidablik": "football",
    "noah": "football",
    "hamrun spartans": "football",
    "samsunspor": "football",
    "fc midtjylland": "football",
    # Hockey
    "ishockey": "hockey",
    "hockey": "hockey",
    "nhl": "hockey",
    "shl": "hockey",
    "hockeyallsvenskan": "hockey",
    "hockeyettan": "hockey",
    "tre kronor": "hockey",
    "khl": "hockey",
    "hockey-vm": "hockey",
    "ishockey-vm": "hockey",
    "channel one cup": "hockey",
    "karjala cup": "hockey",
    "karjala tournament": "hockey",
    "euro hockey tour": "hockey",
    "beijer hockey games": "hockey",
    # Basketball
    "basket": "basketball",
    "nba": "basketball",
    "euroleague": "basketball",
    # Tennis
    "tennis": "tennis",
    "wimbledon": "tennis",
    "us open tennis": "tennis",
    "australian open": "tennis",
    "roland garros": "tennis",
    "atp": "tennis",
    "wta": "tennis",
    # Golf
    "golf": "golf",
    "pga": "golf",
    "lpga": "golf",
    "ryder cup": "golf",
    # Handball - leagues and keywords
    "handboll": "handball",
    "handball": "handball",
    "handbollsligan": "handball",
    "ehf": "handball",
    "hk malmö": "handball",
    "hk malmo": "handball",
    "ystads if": "handball",
    "hif karlskrona": "handball",
    "ifk skövde": "handball",
    "ifk skovde": "handball",
    "ov helsingborg": "handball",
    # German handball clubs
    "sg flensburg": "handball",
    "flensburg-handewitt": "handball",
    "füchse berlin": "handball",
    "fuchse berlin": "handball",
    "thw kiel": "handball",
    "rhein-neckar löwen": "handball",
    "sc magdeburg": "handball",
    "mt melsungen": "handball",
    "gwd minden": "handball",
    "tus n-lübbecke": "handball",
    "hsg wetzlar": "handball",
    "vfl gummersbach": "handball",
    # Motorsport
    "formel 1": "motorsport",
    "formel 2": "motorsport",
    "formel 3": "motorsport",
    "f1": "motorsport",
    "motogp": "motorsport",
    "moto2": "motorsport",
    "moto3": "motorsport",
    "rally": "motorsport",
    "rallycross": "motorsport",
    "nascar": "motorsport",
    "indycar": "motorsport",
    "dtm": "motorsport",
    "formel e": "motorsport",
    "wrc": "motorsport",
    # Cycling
    "cykling": "cycling",
    "tour de france": "cycling",
    "giro": "cycling",
    "vuelta": "cycling",
    # Winter sports - Cross-country skiing
    "skidor": "skiing",
    "längdskidor": "skiing",
    "längdskidåkning": "skiing",
    "world cup skidor": "skiing",
    # Winter sports - Biathlon
    "skidskytte": "biathlon",
    "biathlon": "biathlon",
    # Winter sports - Alpine
    "alpint": "alpine",
    "slalom": "alpine",
    "störtlopp": "alpine",
    "super-g": "alpine",
    "storslalom": "alpine",
    "utför": "alpine",
    # Winter sports - Freestyle skiing (ski cross, moguls, etc)
    "ski cross": "freestyle_skiing",
    "skicross": "freestyle_skiing",
    "freestyle": "freestyle_skiing",
    "freeski": "freestyle_skiing",
    "mogul": "freestyle_skiing",
    "buckelpist": "freestyle_skiing",
    "halfpipe": "freestyle_skiing",
    "slopestyle": "freestyle_skiing",
    "big air": "freestyle_skiing",
    # Winter sports - Ski jumping
    "backhoppning": "ski_jumping",
    "skidflygning": "ski_jumping",
    "ski jumping": "ski_jumping",
    "skiflying": "ski_jumping",
    "hopptävling": "ski_jumping",
    # Winter sports - Nordic combined
    "nordisk kombination": "nordic_combined",
    "nordic combined": "nordic_combined",
    # Winter sports - Other
    "curling": "curling",
    "vintersport": "winter_sports",
    "snowboard": "snowboard",
    # Winter sports - Speed skating
    "skridskor": "speed_skating",
    "skridsko": "speed_skating",
    "speed skating": "speed_skating",
    "short track": "speed_skating",
    # Athletics
    "friidrott": "athletics",
    "friidrotts": "athletics",
    "maraton": "athletics",
    "diamond league": "athletics",
    # Swimming
    "simning": "swimming",
    "sim-": "swimming",
    # Combat
    "boxning": "boxing",
    "tungviktsboxning": "boxing",
    "mma": "mma",
    "ufc": "mma",
    # American sports
    "nfl": "american_football",
    "super bowl": "american_football",
    "mlb": "baseball",
    "baseball": "baseball",
    # Other sports
    "volleyboll": "volleyball",
    "bordtennis": "table_tennis",
    "badminton": "badminton",
    "rugby": "rugby",
    "trav": "horse_racing",
    "galopp": "horse_racing",
    "horse racing": "horse_racing",
    "hästsport": "horse_racing",
    "snooker": "snooker",
    "biljard": "snooker",
    "dart": "darts",
    "padel": "padel",
    "innebandy": "floorball",
    "bandy": "bandy",
    "e-sport": "esports",
    "esport": "esports",
    "counter-strike": "esports",
    "league of legends": "esports",
    "segling": "sailing",
}
